//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cashier_n_data
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public itemData()
        {
            this.itemPictures = new HashSet<itemPicture>();
            this.itemBarcodes = new HashSet<itemBarcode>();
        }
    
        public int itemid { get; set; }
        public string itemName { get; set; }
        public string itemPrice { get; set; }
        public string itemDescription { get; set; }
        public string itemBarcode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<itemPicture> itemPictures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<itemBarcode> itemBarcodes { get; set; }
    }
}
