//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cashier_n_data
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemBarcode
    {
        public int Id { get; set; }
        public int itemid { get; set; }
        public byte[] itemBarcode1 { get; set; }
    
        public virtual itemData itemData { get; set; }
    }
}
