//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cashier_n_data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginData
    {
        public int userid { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> lastlogin { get; set; }
    }
}
